language: elixir

elixir:
  - 1.8
  - 1.7
  - 1.6
  - 1.5

otp_release:
  - 21.1
  - 20.3
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.5
      otp_release: 21.1
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 18.3

env:
  global:
    - MIX_ENV=test

notifications:
  email: false

before_cache:
  - rm -rf _build/$MIX_HOME/lib

cache:
  directories:
    - _build/$MIX_HOME

script:
  - mix test
  - mix credo
  - mix dialyzer --halt-exit-status
  - if ! [[ `elixir -v` = *"1.5"* ]]; then mix format --check-formatted; fi
